import assert from 'node:assert/strict';
import {test} from 'node:test';
import {registerHooks} from 'node:module';
registerHooks({resolve(s,c,n){return n(s.startsWith('.')&&c.parentURL?.includes('/src/')&&!/\.[a-z]+$/.test(s)?new URL(s+'.ts',c.parentURL).href:s,c)}});
test('T04 shared transport preserves late hash, excludes duplicates, blocks all simulation mutations and delegates one recovery',async()=>{
 const h=await import('../src/hold.ts'),l=await import('../src/lifecycle.ts'),e=await import('../src/evidence.ts'),{createAssetProviders}=await import('../src/transport.ts'),{keccak256}=await import('viem');
 const input=h.createHoldInput({block:'40224162',timestamp:'1788790000'}),calldata=await h.holdCalldata('create-hold',input),hash='0x'+'1'.repeat(64);
 const initial={schemaVersion:1,kind:'t04-transaction',chainId:296,operationId:'transport-fixture',startedAt:new Date().toISOString(),action:'create-hold',status:'awaiting-signature',input,signerRole:'Seller',calldataDigest:keccak256(calldata)};
 const controller=new AbortController();let sends=0,finish;const updates=[];
 const options={wallet:{provider:{request:async()=>{sends++;return new Promise(r=>finish=r)}}},signer:l.accounts.Seller.address,securityAddress:l.securityAddress,calldata,reads:await h.holdSdkReads(input),initial,sanitize:e.holdEvidence,update:r=>updates.push(r),checkCurrent:async()=>{},signal:controller.signal,recoverAfterHash:true,verifyReceipt:h.verifyHoldReceipt};
 const p=await createAssetProviders(options),tx={from:l.accounts.Seller.address,to:l.securityAddress,data:calldata,value:'0x0'};
 for(const method of ['personal_sign','eth_signTypedData_v4','eth_sendRawTransaction','wallet_switchEthereumChain'])await assert.rejects(p.browser.send(method,[]));
 await assert.rejects(p.browser.send('eth_sendTransaction',[{...tx,from:l.accounts.Admin.address}]));assert.equal(sends,0);
 const pending=p.browser.send('eth_sendTransaction',[tx]);while(!finish)await new Promise(r=>setImmediate(r));await assert.rejects(p.browser.send('eth_sendTransaction',[tx]));controller.abort();finish(hash);await pending;
 assert.equal(sends,1);assert.equal(p.getRecord().transactionHash,hash);assert.equal(updates.at(-1).status,'pending');p.close();
 const q=await createAssetProviders({...options,signal:new AbortController().signal,readOnly:true});
 await assert.rejects(q.browser.send('eth_sendTransaction',[tx]));assert.equal(q.wasAttempted(),false);assert.equal(sends,1);q.close();
 const r=await createAssetProviders({...options,signal:new AbortController().signal,wallet:{provider:{request:async()=>hash}}});await r.browser.send('eth_sendTransaction',[tx]);
 await assert.rejects(r.browser.getTransaction(hash),error=>error.code==='CANCELLED');assert.equal(r.getRecord().status,'pending');r.close();
});
