import NovaFlow from './NovaFlow';
import {useEffect,useRef,useState} from 'react';
import {motion,useReducedMotion} from 'motion/react';
import {accounts} from './lifecycle';
import type {Roles} from './guards';
import {hbar,type Match} from './market';
import {loadSettlement,saveSettlement,prepareSettlement,submitSettlement,recoverSettlement,settlementAction,settlementLabels,settlementStatus,settlementStorageKey,type Settlement,type SettlementDeployment,type SettlementOperation,type SettlementReview,type SavedSettlement} from './settlement';
export const accountLabel=(a:string)=>a===accounts.Seller.address?'Seller account':a===accounts.Buyer.address?'Buyer account':a===accounts.Admin.address?'Admin account':'Not connected';
export default function SettlementPanel({match,settlement,deployment,pendingOperation,roles,owner,session,online,locked,eligible,onNewOrder,onUpdated}:{match?:Match;settlement?:Settlement;deployment?:SettlementDeployment;pendingOperation?:SettlementOperation;roles:Roles;owner:string;session:number;online:boolean;locked:boolean;eligible:boolean;onNewOrder:()=>void;onUpdated:()=>void}){
 const [saved,setSaved]=useState<SavedSettlement>(),[review,setReview]=useState<SettlementReview>(),[approved,setApproved]=useState(false),[phase,setPhase]=useState<'preparing'|'wallet'|'verifying'>(),[problem,setProblem]=useState(''),[hash,setHash]=useState('');
 const heading=useRef<HTMLHeadingElement>(null),controller=useRef<AbortController|undefined>(undefined),reduced=useReducedMotion(),epoch=useRef(0);
 const preview=typeof window!=='undefined'&&window.location.origin==='http://127.0.0.1:4173'&&import.meta.env.PROD;
 useEffect(()=>{const load=()=>{try{const v=loadSettlement();setSaved(v);setHash(v?.operation.hash??'');}catch{setProblem('Stored operation is invalid. Preserve its public intent and recover the original hash.');}};load();const listener=(e:StorageEvent)=>{if(e.key===settlementStorageKey||e.key===null){load();setReview(undefined);setApproved(false);}};window.addEventListener('storage',listener);return()=>{controller.current?.abort();window.removeEventListener('storage',listener);};},[]);
 useEffect(()=>{epoch.current++;controller.current?.abort();setReview(undefined);setApproved(false);heading.current?.focus();},[session,owner,match?.id]);
 const update=(s:SavedSettlement)=>{setSaved(s);setHash(s.operation.hash);onUpdated();};
 const now=BigInt(Math.floor(Date.now()/1000));const stage=settlement?settlementStatus(settlement,now):'Unprepared';
 const terminal=['Settled','Cancelled','Reclaimed','Returned'].includes(stage);
 const unknown=!!saved?.attempted&&!saved.rejected&&!['verified','reverted'].includes(saved.operation.status);
 const pendingOther=!!pendingOperation&&pendingOperation.id!==saved?.operation.id;
 const next=!deployment?'deploy':settlement?settlementAction(settlement,owner,now):owner===match?.seller?'lock':undefined;
 const selectedSaved=saved&&(match?saved.operation.settlementId===match.id:saved.operation.action==='deploy');
 const working=phase!==undefined;
 const progress=phase==='preparing'?'Checking account and match terms…':phase==='wallet'&&!(selectedSaved&&saved.operation.hash)?'Waiting for manual MetaMask approval…':'Verifying the original transaction…';
 const blocked=working||locked||!online||!preview||unknown||pendingOther||!eligible;
 async function prepare(action:SettlementOperation['action']){if(blocked)return;const c=new AbortController();controller.current=c;const rev=epoch.current;setPhase('preparing');setApproved(false);setProblem('');try{const r=await prepareSettlement(roles,action,match,c.signal);if(rev===epoch.current&&!c.signal.aborted){setReview(r);setSaved(loadSettlement());heading.current?.focus();}}catch(e){if(!c.signal.aborted)setProblem(e instanceof Error?e.message:'Preparation unavailable.');try{setSaved(loadSettlement());}catch{/* Keep failure visible. */}}finally{setPhase(undefined);onUpdated();}}
 async function send(){if(!review||!approved||blocked)return;setPhase('wallet');setApproved(false);setProblem('');const c=new AbortController();controller.current=c;try{await submitSettlement(review,c.signal,update);}catch(e){setProblem(e instanceof Error?e.message:'Operation incomplete. Query the original hash.');}finally{setReview(undefined);setPhase(undefined);onUpdated();}}
 async function recover(){if(working||locked)return;setPhase('verifying');setProblem('');try{await recoverSettlement(AbortSignal.timeout(180000),update,hash.trim());}catch(e){setProblem(e instanceof Error?e.message:'Verification pending. Retain the original transaction.');}finally{setPhase(undefined);onUpdated();}}
 function exportEvidence(){const value={settlement,operation:selectedSaved?saved?.operation:undefined};const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='holdbook-settlement-public.json';a.click();URL.revokeObjectURL(url);}
 const message=!eligible?'Historical match · No settlement is permitted for pre-deployment orders.':!deployment?'Admin prepares one settlement contract.':terminal?stage:unknown?'Transaction submitted or unknown · Verify the original operation':stage==='Expired · Reclaim required'?'Expiry stops payment. NOVA remains locked until reclaim is verified.':stage==='Locked'?'Step 2 of 2 · Seller confirms the match terms':stage==='Ready'?(owner===match?.buyer?'Review payment':'Waiting for buyer'):(owner===match?.seller?'Step 1 of 2 · Lock NOVA for this match':'Waiting for seller');
 return <section className="market-ticket settlement-ticket" aria-labelledby="settlement-heading">
  <div className="market-account"><strong>{accountLabel(owner)}{match&&owner===match.seller?' · Selling this match':match&&owner===match.buyer?' · Buying this match':''}</strong><span>Testnet 296 · Manual approval</span></div>
  <h3 id="settlement-heading" ref={heading} tabIndex={-1}>{review?'Review '+(review.operation.action==='settle'?'payment':'settlement'):match?'Match '+match.id:'Settlement setup'}</h3>
  {match&&<NovaFlow key={match.id} status={stage} quantity={match.quantity} total={hbar(match.notional)}/>}
  <motion.div key={review?'review':terminal?'result':'progress'} initial={{opacity:reduced?1:0}} animate={{opacity:1}} transition={{duration:reduced?0:0.16}} className="hb:space-y-4">
   <p role="status"><strong>{message}</strong></p>
   {match&&<><p className="settlement-amount">{match.quantity} NOVA <span>for {hbar(match.notional)} HBAR</span></p><dl><div><dt>Unit price</dt><dd>{hbar(match.price)} HBAR / NOVA</dd></div><div><dt>NOVA</dt><dd>{terminal?(stage==='Settled'?'Delivered · verified':'Returned · verified'):settlement&&['Locked','Ready'].includes(settlement.status)?'Locked · verified':'Not locked'}</dd></div><div><dt>HBAR</dt><dd>{stage==='Settled'?'Paid · verified':'Not paid'}</dd></div><div><dt>Required account</dt><dd>{terminal?'None · complete':accountLabel(!deployment?accounts.Admin.address:stage==='Ready'&&now<BigInt(settlement!.terms.expiry)?match.buyer:match.seller)}</dd></div>{settlement&&<div><dt>Expires (UTC)</dt><dd>{new Date(Number(settlement.terms.expiry)*1000).toISOString()}</dd></div>}</dl></>}
   {review&&<><p>{settlementLabels[review.operation.action]} · {accountLabel(review.operation.sender)}</p><p>Wallet value: {hbar((BigInt(review.operation.value)/10000000000n).toString())} HBAR + network fee</p><label className="review-check"><input type="checkbox" checked={approved} disabled={blocked} onChange={e=>setApproved(e.target.checked)}/>I reviewed the account, Testnet 296, quantities, price, expiry and transaction details. No unknown transaction is outstanding in MetaMask.</label><div className="actions"><button disabled={blocked||!approved} onClick={send}>Approve in MetaMask</button><button className="secondary" disabled={working} onClick={()=>{setReview(undefined);setApproved(false);}}>Back to match</button></div></>}
   {!review&&!terminal&&next&&(next!=='deploy'||owner===accounts.Admin.address)&&<button disabled={blocked} onClick={()=>prepare(next)}>{next==='settle'?'Review payment':settlementLabels[next]}</button>}
   {!review&&settlement&&owner===settlement.terms.seller&&!terminal&&now<BigInt(settlement.terms.expiry)&&['Locked','Ready'].includes(settlement.status)&&<div className="actions"><button className="secondary" disabled={blocked} onClick={()=>prepare(settlement.status==='Locked'?'orphan':'cancel')}>{settlement.status==='Locked'?'Return unregistered Hold':'Cancel settlement'}</button></div>}
   {selectedSaved&&saved.operation.evidence&&<p>Network fee: {hbar(saved.operation.evidence.feeTinybars)} HBAR · <a href={'https://hashscan.io/testnet/transaction/'+saved.operation.hash} target="_blank" rel="noreferrer">Transaction evidence</a></p>}
   {working&&<p role="status" className="operation-progress">{progress}<span className="operation-spinner" aria-hidden="true"/></p>}
   {problem&&<p role="alert">{problem}</p>}
   {!online&&<p>Settlement service unavailable. Last received data is retained; actions requiring fresh data are disabled.</p>}
   {!preview&&<p>Use <a href="http://127.0.0.1:4173">production preview</a> for manual transactions.</p>}
  </motion.div>
  {pendingOther&&<div className="pending-notice"><p>An existing {pendingOperation!.action} operation requires recovery.</p><button className="secondary" disabled={working} onClick={()=>{const v={operation:pendingOperation!,attempted:true,rejected:false};saveSettlement(v);update(v);}}>Load original operation for query</button></div>}
  {saved&&<details open={unknown} className="transaction-details"><summary>Original operation · {saved.operation.status}</summary><p className="address">{saved.operation.id}</p><p>Querying never resubmits. An unknown transaction remains pending after the review expires.</p><label className="text-field">Original transaction hash<input value={hash} maxLength={66} onChange={e=>setHash(e.target.value)} disabled={working||!!saved.operation.hash}/></label><button className="secondary" disabled={working||locked} onClick={recover}>Query original operation</button></details>}
  <details className="transaction-details"><summary>Match terms and public evidence</summary><pre>{JSON.stringify({match,settlement,deployment,operation:review?.operation??(selectedSaved?saved?.operation:undefined)},null,2)}</pre><button className="secondary" onClick={exportEvidence}>Download public settlement evidence</button></details>
  <div className="actions"><button className="secondary" disabled={working} onClick={onNewOrder}>New order</button></div>
 </section>;
}
