import {useState} from 'react';
import {createRoot} from 'react-dom/client';
import snapshot from './showcase.json';
import './styles.css';
function Showcase(){
 const [selected,setSelected]=useState(snapshot.cases[0].id),item=snapshot.cases.find(c=>c.id===selected)!;
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='holdbook-testnet-snapshot.json';a.click();URL.revokeObjectURL(url);}
 return <><a className="skip-link" href="#main">Skip to evidence</a><header className="showcase-header"><a href="#main">HoldBook</a><span>Full-stack engineering · Hedera Testnet</span></header><main id="main" className="showcase-main">
  <section aria-labelledby="purpose"><h1 id="purpose">A match is only the beginning.</h1><p className="showcase-lead">Follow a fictional equity order from a signed intent to matched terms, locked shares and atomic payment. Every wallet approval remains a human decision.</p><p>React and TypeScript · Go · PostgreSQL · Solidity · ATS SDK</p></section>
  <section aria-labelledby="verified"><h2 id="verified">{snapshot.historical.title}</h2><p><strong>{snapshot.label}</strong> · {new Date(snapshot.recordedAt).toISOString().slice(0,10)} · Block {snapshot.historical.block}</p><p>The earlier fixed trade is verified. The four new per-match T08 cases below await manual acceptance.</p><ol className="showcase-timeline">{snapshot.historical.timeline.map(t=><li key={t.hash}><strong>{t.action}</strong><span>Block {t.block} · <a href={'https://hashscan.io/testnet/transaction/'+t.hash} target="_blank" rel="noreferrer">View transaction</a></span></li>)}</ol><dl className="showcase-balances"><div><dt>Seller available / held</dt><dd>84 / 0 NOVA</dd></div><div><dt>Buyer available / held</dt><dd>16 / 0 NOVA</dd></div></dl><a href={snapshot.historical.report} target="_blank" rel="noreferrer">Read original verification and limitations</a></section>
  <section aria-labelledby="cases"><h2 id="cases">Per-match settlement cases</h2><p>Fresh orders, an exact ATS Hold and a 30-minute deadline for each match. Expected quantities below are the acceptance plan; they are not completed transactions.</p><div className="showcase-case-picker" role="group" aria-label="Settlement case">{snapshot.cases.map(c=><button className="secondary" key={c.id} aria-pressed={c.id===selected} onClick={()=>setSelected(c.id)}>{c.title}</button>)}</div><article className="showcase-case" aria-live="polite"><h3>{item.title}</h3><p>{item.quantity} NOVA @ {item.unitPriceHBAR} HBAR</p><p><strong>{item.status}</strong></p><p>No T08 transaction evidence has been recorded for this case.</p></article></section>
  <section aria-labelledby="architecture"><h2 id="architecture">Where each decision lives</h2><ol className="showcase-architecture"><li><h3>Browser + MetaMask</h3><p>Reviews exact terms, checks account and network, saves intent and asks for one manual approval.</p></li><li><h3>Go + PostgreSQL</h3><p>Authenticates order intent, matches by price and time, persists operations and independently checks public chain evidence.</p></li><li><h3>ATS + settlement contract</h3><p>Validates the Hold and parties, delivers NOVA and pays HBAR atomically. Expired locked shares require a verified return.</p></li></ol></section>
  <section aria-labelledby="evidence"><h2 id="evidence">Inspect the evidence</h2><p>This static snapshot has no wallet connection, local API or transaction controls. It describes fictional Testnet assets and synthetic KYC, with no real securities or legal compliance claim.</p><button className="secondary" onClick={download}>Download public snapshot JSON</button><p><a href="https://github.com/outsider987/hedera-rwa-secondary-market" target="_blank" rel="noreferrer">Source, setup and attribution</a></p></section>
 </main><footer className="showcase-main"><p>Data recorded {snapshot.recordedAt}. Historical results do not describe current balances.</p></footer></>;
}
createRoot(document.getElementById('root')!).render(<Showcase/>);
